---

  - name: find all extension files
    find:
      paths: "/tmp/lidop/extensions"
      patterns: 
        - "*.yml"
        - "*.yaml"
      recurse: true
    register: extension_files
    when: node == "master"

  - name: print files
    debug:
      msg: "{{ extension_files.files }}"
    when: node == "master"

  - name: include extension_files files
    include_tasks: "{{ item.path }}"
    static: no
    with_items: "{{ extension_files.files }}"

  - name: include extension_files files
    template:
      src: "{{ item.path }}"
      dest: "{{ item.path | replace('.j2','') }}"
    with_items: "{{ extension_files.files }}"
    when: node == "master"