---

- name: Install Software
  block:
    - name: Install required packages
      apt: 
        name: "{{ packages }}"
        update_cache: yes 
        state: present
      vars:
        packages:
          - default-jre
          - nfs-kernel-server
      when: install_mode == "online"
  
  tags: software