---


- name: Install required packages
  apt: 
    name: "{{ packages }}"
    update_cache: yes 
    state: present
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg-agent
  when: install_mode == "online"

- name: install docker-py
  shell: pip install docker
  when: install_mode == "online"
  
- name: install docker-py
  shell: pip install docker-compose
  when: install_mode == "online"

- name: install python-consul
  shell: pip install python-consul
  when: install_mode == "online"

- name: ensure repository key is installed
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present
  when: install_mode == "online"
  
- name: ensure docker registry is available
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
    update_cache: yes
  when: install_mode == "online"

- name: ensure docker and dependencies are installed
  apt: 
    name: docker-ce 
    update_cache: yes
  when: install_mode == "online"

- name: Installing docker compose
  pip:
    name: docker-compose
    state: present
  when: install_mode == "online"

- name: Ensure docker daemon options used (systemd)
  lineinfile:
    backrefs: yes
    dest: /lib/systemd/system/docker.service
    regexp: '^ExecStart='
    line: ExecStart=/usr/bin/dockerd -H unix:// -H tcp://0.0.0.0:2375 --api-cors-header="*" --insecure-registry registry.service.lidop.local:5000
  notify: 
    - Reload systemd
    - Restart docker

- meta: flush_handlers

- name: Add LiDOP user to docker group
  command: "usermod -aG docker {{ root_user }}"
  changed_when: false
