---

########################################################################
- name: Start web
########################################################################
  block:

  - name: Create folders
    file:
      state: "directory"
      path: "/var/lidop/{{ item }}"
      owner: "{{ root_user }}"
      group: "{{ root_user }}"
      mode: '0775'
    with_items:
      - /www/certbot
      - /certs/live
    when: node == "master"

  - name: pull image
    shell: "docker pull livingdevops/lidop.nginx:{{ docker_image_version }}"
    when: 
      - install_mode == "online"
      - node == "master"

  - name: tag image
    shell: "docker tag livingdevops/lidop.nginx:{{ docker_image_version }} registry.service.lidop.local:5000/lidop/nginx:{{ docker_image_version }}"
    when: node == "master"

  - name: push image
    shell: "docker push registry.service.lidop.local:5000/lidop/nginx:{{ docker_image_version }}"
    when: node == "master"

  - name: pull image
    shell: "docker pull registry.service.lidop.local:5000/lidop/nginx:{{ docker_image_version }}"
    when: node == "worker"

  - name: create ssl certificate with letsencrypt
    shell: >
      docker run --rm --net host -i -v /var/lidop/certs:/etc/letsencrypt  certbot/certbot 
      certonly --standalone -d {{ item }}{{ domain_name }} -m lidop@{{ domain_name }} --agree-tos -n
    when: 
      - certificate_creation == "letsencrypt"
      - node == "master"
    with_items:
      - ""

  - name: create self signed certificate
    shell: |
      mkdir /var/lidop/certs/live/{{ item }}{{ domain_name }}
      openssl genrsa -out /var/lidop/certs/live/{{ item }}{{ domain_name }}/privkey.pem 2048
      openssl req -new -key /var/lidop/certs/live/{{ item }}{{ domain_name }}/privkey.pem -out /var/lidop/certs/live/{{ item }}{{ domain_name }}.csr -subj "/C=CH/ST=Zurich/L=Zurich/O=Global Security/OU=IT Department/CN={{ item }}{{ domain_name }}"
      openssl x509 -req -in /var/lidop/certs/live/{{ item }}{{ domain_name }}.csr -CA /tmp/lidop/configs/certs/rootCA.pem -CAkey /tmp/lidop/configs/certs/rootCA.key -CAcreateserial -out /var/lidop/certs/live/{{ item }}{{ domain_name }}/fullchain.pem -days 1825 -sha256 -extfile /var/lidop/certs/v3.ext -passin pass:lidop
    when: 
      - certificate_creation == "self"
      - node == "master"
    with_items:
      - ""

  - name: start webservice
    shell: docker stack deploy -c /var/lidop/templates/web.yml portal
    when: node == "master"

  - name: "wait for web to come up"
    uri:
      url: "http://{{ ipaddress }}:80"
      status_code: 401
    register: result
    until: result.status == 401
    retries: 100
    delay: 5
    when: node == "master"

  tags: web
